version: '2'
services:
  registry:
    image: registry:2.6
    container_name: registry
    restart: always
    networks:
      - front
    volumes:
      - registry-data:/var/lib/registry
    environment:
      - REGISTRY_LOG_LEVEL=${REGISTRY_LOG_LEVEL}
      - REGISTRY_AUTH_TOKEN_REALM=${REGISTRY_AUTH_TOKEN_REALM}
      - REGISTRY_AUTH_TOKEN_SERVICE=${REGISTRY_AUTH_TOKEN_SERVICE}
      - REGISTRY_AUTH_TOKEN_ISSUER=${REGISTRY_AUTH_TOKEN_ISSUER}
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=${REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE}
      - REGISTRY_STORAGE_DELETE_ENABLED=${REGISTRY_STORAGE_DELETE_ENABLED}

      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}


volumes:
  registry-data:

networks:
  front:
    external:
      name: proxy_front
